import random

LANGUAGES = ("ru", "en", "he")
DEFAULT_LANGUAGE = "en"

LANGUAGE_NAMES = {"ru": "Русский", "en": "English", "he": "עברית"}

TEXTS: dict[str, dict[str, str]] = {
    "ru": {
        "language_prompt": "🌐 Выберите язык / Choose language / בחר שפה:",
        "language_saved": "Готово ✅",
        "welcome": (
            "Привет! Я помогу считать калории и БЖУ.\n\n"
            "Я использую твой личный OpenAI API-ключ для распознавания еды по тексту и фото — "
            "все траты идут с твоего собственного баланса OpenAI, ключ хранится в зашифрованном виде.\n\n"
            "Давай настроим профиль."
        ),
        "welcome_back": "С возвращением! Просто напиши, что съел, или выбери пункт меню.",
        "ask_api_key": (
            "Введите ваш OpenAI API-ключ (он используется только для ваших собственных запросов "
            "и хранится в зашифрованном виде):"
        ),
        "checking_key": "Секунду, проверяю ключ... 🔑",
        "key_invalid": "Ключ невалиден. Пожалуйста, введите корректный OpenAI API-ключ:",
        "key_check_failed": "Не удалось связаться с OpenAI, чтобы проверить ключ. Попробуйте отправить ключ ещё раз чуть позже:",
        "key_accepted_ask_weight": "Ключ принят ✅\n\nТеперь введите ваш вес в кг (например, 78.5):",
        "settings_ask_new_api_key": "Введите новый OpenAI API-ключ:",
        "ask_weight": "Введите ваш вес в кг (например, 78.5):",
        "weight_invalid": "Не похоже на вес. Введите число в кг, например 78.5:",
        "ask_height": "Рост в см (например, 178):",
        "height_invalid": "Не похоже на рост. Введите число в см, например 178:",
        "ask_age": "Возраст (полных лет):",
        "age_invalid": "Не похоже на возраст. Введите число лет, например 30:",
        "ask_gender": "Пол:",
        "ask_activity": "Уровень активности:",
        "ask_goal": "Какая у вас цель?",
        "ask_deficit_loss": "На сколько % урезать калорийность?",
        "ask_deficit_gain": "На сколько % увеличить калорийность?",
        "settings_ask_deficit": "На сколько % изменить калорийность?",
        "gender_male": "Мужской",
        "gender_female": "Женский",
        "activity_sedentary": "Сидячий",
        "activity_light": "Лёгкая активность",
        "activity_moderate": "Умеренная",
        "activity_high": "Высокая",
        "activity_very_high": "Очень высокая",
        "goal_loss": "Похудение",
        "goal_gain": "Набор массы",
        "goal_maintain": "Поддержание",
        "gender_saved": "Пол: {label} ✅",
        "activity_saved": "Активность: {label} ✅",
        "goal_saved": "Цель: {label} ✅",
        "deficit_saved": "% дефицита/профицита: {value} ✅",
        "deficit_ai_suggest": "предложит ИИ",
        "computing_targets": "Секунду, считаю твою норму калорий и БЖУ... 🧮",
        "targets_proposed_header": "Предложенные цифры на день:",
        "targets_current_header": "Текущие целевые значения:",
        "targets_line": "{label}: {value} {unit}",
        "targets_accept_or_edit": "Примите как есть или отредактируйте отдельные значения:",
        "targets_saved": "Норма сохранена, отличный старт! ✅",
        "targets_field_prompt": "Введите новое значение для «{field}»:",
        "targets_field_invalid": "Введите положительное целое число:",
        "onboarding_complete": "Профиль настроен! Теперь просто пишите мне, что съели, в свободной форме.",
        "fallback_explanation": "ИИ временно недоступен — показан примерный расчёт, значения можно поправить вручную.",
        "target_kcal": "Калории",
        "target_protein": "Белки",
        "target_fat": "Жиры",
        "target_carbs": "Углеводы",
        "abbr_protein": "Б",
        "abbr_fat": "Ж",
        "abbr_carbs": "У",
        "unit_kcal": "ккал",
        "unit_g": "г",
        "settings_incomplete_profile": "Сначала нужно закончить настройку профиля через /start.",
        "settings_title": "⚙️ Настройки:",
        "settings_saved": "Сохранено ✅\n\n⚙️ Настройки:",
        "settings_field_basic_info": "📋 Основные данные",
        "settings_field_goal_activity": "🎯 Цель и активность",
        "settings_field_weight": "Вес",
        "settings_field_height": "Рост",
        "settings_field_age": "Возраст",
        "settings_field_gender": "Пол",
        "settings_field_activity": "Активность",
        "settings_field_goal": "Цель",
        "settings_field_deficit": "% дефицита/профицита",
        "settings_field_targets": "БЖУ вручную",
        "settings_field_update_weight": "⚖️ Обновить вес",
        "settings_field_api_key": "🔑 API-ключ",
        "settings_field_language": "🌐 Язык",
        "food_no_api_key": "Сначала укажи свой OpenAI API-ключ через ⚙️ Настройки.",
        "calculating": "Секунду, считаю калории... 🧮",
        "food_item_parse_failed": "Хм, не смог разобрать «{text}»: {error}",
        "food_parse_network_error": "Не удалось связаться с OpenAI. Попробуй отправить сообщение ещё раз, пожалуйста.",
        "food_nothing_recognized": "Не получилось ничего распознать 🤔 Уточни, пожалуйста, что именно ты съел и сколько грамм.",
        "ai_no_items_recognized": "Не удалось распознать продукты в сообщении.",
        "ai_invalid_response": "Модель вернула некорректный ответ, попробуй переформулировать сообщение.",
        "food_fix_prompt": "Хорошо, пришли исправленное описание того, что съел.",
        "food_saved": "Готово, записал! 🙌",
        "food_summary_header": "Вот что получилось 🍽\n",
        "food_summary_total": "Итого",
        "photo_ask_grams": "А сколько грамм ты съел?",
        "photo_lost_state": "Ой, что-то пошло не так — отправь фото ещё раз, пожалуйста.",
        "photo_recognizing": "Секунду, смотрю на фото... 👀",
        "photo_unreadable_suffix": "\nОпиши, пожалуйста, что съел, текстом — так и посчитаю.",
        "photo_fix_prompt": "Хорошо, пришли фото ещё раз или опиши съеденное текстом.",
        "photo_no_grams_hint": "Количество грамм не указано, оцени по фото, если возможно.",
        "btn_food_ok": "✅ Всё верно",
        "btn_food_fix": "✏️ Исправить",
        "remaining_header": "📊 Остаток на сегодня:",
        "remaining_line": "{label}: {eaten}/{target} {unit} (осталось {remaining} {unit})\n{bar}",
        "today_entries_header": "Записи за сегодня (нажми, чтобы удалить):",
        "entry_deleted": "Удалено ✅",
        "manage_entries_button": "✏️ Изменить/удалить запись",
        "confirm_delete_prompt": "Удалить «{name}» — {kcal} {unit}?",
        "confirm_yes": "✅ Да, удалить",
        "confirm_no": "❌ Отмена",
        "history_choose_period": "За какой период показать историю?",
        "history_no_entries": "📅 Нет записей за период {date_from} — {date_to}.",
        "history_header": "📅 История ({date_from} — {date_to}):\n",
        "history_total": "Итого: {kcal} ккал, Б {protein} / Ж {fat} / У {carbs}{weight_part}\n",
        "history_weight_part": ", вес {weight} кг",
        "history_period_today": "Сегодня",
        "history_period_yesterday": "Вчера",
        "history_period_week": "За неделю",
        "weight_checkin_prompt": "Как твой вес на этой неделе?",
        "weight_checkin_now": "Указать вес сейчас",
        "weight_checkin_skip": "Пропустить",
        "weight_checkin_ask": "Введите текущий вес в кг:",
        "weight_checkin_skipped": "Хорошо, спрошу ещё раз позже. Можно внести вес в любой момент через ⚙️ Настройки.",
        "weight_checkin_saved": "Записал: {value} кг, отлично! 💪",
        "weight_reminder": "Не забудь указать вес на этой неделе 🙂",
        "btn_settings": "⚙️ Настройки",
        "btn_remaining": "📊 Остаток на сегодня",
        "btn_history": "📅 История",
        "help_text": (
            "Просто напиши, что съел — я распознаю продукты и посчитаю калории/БЖУ.\n"
            "Можно прислать фото этикетки с указанием, сколько грамм ты съел.\n\n"
            "📊 Остаток на сегодня — сколько калорий/БЖУ осталось до нормы.\n"
            "📅 История — статистика за прошлые дни.\n"
            "⚙️ Настройки — изменить вес/рост/возраст/цель/БЖУ/API-ключ."
        ),
        "fallback_text": "Не совсем понял. Напиши, что съел, пришли фото еды с этикеткой, или воспользуйся /help.",
        "generic_error": "Произошла ошибка. Попробуй ещё раз чуть позже.",
    },
    "en": {
        "language_prompt": "🌐 Выберите язык / Choose language / בחר שפה:",
        "language_saved": "Done ✅",
        "welcome": (
            "Hi! I'll help you track calories and macros.\n\n"
            "I use your personal OpenAI API key to recognize food from text and photos — "
            "all costs are billed to your own OpenAI balance, and the key is stored encrypted.\n\n"
            "Let's set up your profile."
        ),
        "welcome_back": "Welcome back! Just tell me what you ate, or pick a menu option.",
        "ask_api_key": (
            "Enter your OpenAI API key (it's used only for your own requests "
            "and stored encrypted):"
        ),
        "checking_key": "One sec, checking the key... 🔑",
        "key_invalid": "This key is invalid. Please enter a valid OpenAI API key:",
        "key_check_failed": "Couldn't reach OpenAI to check the key. Please try sending it again shortly:",
        "key_accepted_ask_weight": "Key accepted ✅\n\nNow enter your weight in kg (e.g. 78.5):",
        "settings_ask_new_api_key": "Enter your new OpenAI API key:",
        "ask_weight": "Enter your weight in kg (e.g. 78.5):",
        "weight_invalid": "That doesn't look like a weight. Enter a number in kg, e.g. 78.5:",
        "ask_height": "Height in cm (e.g. 178):",
        "height_invalid": "That doesn't look like a height. Enter a number in cm, e.g. 178:",
        "ask_age": "Age (full years):",
        "age_invalid": "That doesn't look like an age. Enter a number of years, e.g. 30:",
        "ask_gender": "Gender:",
        "ask_activity": "Activity level:",
        "ask_goal": "What's your goal?",
        "ask_deficit_loss": "By how many % should calories be reduced?",
        "ask_deficit_gain": "By how many % should calories be increased?",
        "settings_ask_deficit": "By how many % should calories change?",
        "gender_male": "Male",
        "gender_female": "Female",
        "activity_sedentary": "Sedentary",
        "activity_light": "Light activity",
        "activity_moderate": "Moderate",
        "activity_high": "High",
        "activity_very_high": "Very high",
        "goal_loss": "Weight loss",
        "goal_gain": "Weight gain",
        "goal_maintain": "Maintenance",
        "gender_saved": "Gender: {label} ✅",
        "activity_saved": "Activity: {label} ✅",
        "goal_saved": "Goal: {label} ✅",
        "deficit_saved": "Deficit/surplus %: {value} ✅",
        "deficit_ai_suggest": "AI will suggest",
        "computing_targets": "One sec, calculating your target calories and macros... 🧮",
        "targets_proposed_header": "Proposed daily targets:",
        "targets_current_header": "Current target values:",
        "targets_line": "{label}: {value} {unit}",
        "targets_accept_or_edit": "Accept as is, or edit individual values:",
        "targets_saved": "Targets saved, great start! ✅",
        "targets_field_prompt": "Enter a new value for “{field}”:",
        "targets_field_invalid": "Enter a positive whole number:",
        "onboarding_complete": "Your profile is set up! Just tell me what you ate, in free form.",
        "fallback_explanation": "AI is temporarily unavailable — showing an estimated calculation, you can adjust the values manually.",
        "target_kcal": "Calories",
        "target_protein": "Protein",
        "target_fat": "Fat",
        "target_carbs": "Carbs",
        "abbr_protein": "P",
        "abbr_fat": "F",
        "abbr_carbs": "C",
        "unit_kcal": "kcal",
        "unit_g": "g",
        "settings_incomplete_profile": "Please finish setting up your profile via /start first.",
        "settings_title": "⚙️ Settings:",
        "settings_saved": "Saved ✅\n\n⚙️ Settings:",
        "settings_field_basic_info": "📋 Basic info",
        "settings_field_goal_activity": "🎯 Goal and activity",
        "settings_field_weight": "Weight",
        "settings_field_height": "Height",
        "settings_field_age": "Age",
        "settings_field_gender": "Gender",
        "settings_field_activity": "Activity",
        "settings_field_goal": "Goal",
        "settings_field_deficit": "Deficit/surplus %",
        "settings_field_targets": "Macros manually",
        "settings_field_update_weight": "⚖️ Update weight",
        "settings_field_api_key": "🔑 API key",
        "settings_field_language": "🌐 Language",
        "food_no_api_key": "First set your OpenAI API key via ⚙️ Settings.",
        "calculating": "One sec, calculating calories... 🧮",
        "food_item_parse_failed": "Hmm, couldn't recognize “{text}”: {error}",
        "food_parse_network_error": "Couldn't reach OpenAI. Please try sending the message again.",
        "food_nothing_recognized": "Couldn't recognize anything 🤔 Please clarify what exactly you ate and how many grams.",
        "ai_no_items_recognized": "Couldn't recognize any food items in the message.",
        "ai_invalid_response": "The model returned an invalid response, try rephrasing your message.",
        "food_fix_prompt": "Okay, send a corrected description of what you ate.",
        "food_saved": "Done, saved it! 🙌",
        "food_summary_header": "Here's what I got 🍽\n",
        "food_summary_total": "Total",
        "photo_ask_grams": "And how many grams did you eat?",
        "photo_lost_state": "Oops, something went wrong — please send the photo again.",
        "photo_recognizing": "One sec, looking at the photo... 👀",
        "photo_unreadable_suffix": "\nPlease describe what you ate as text instead, and I'll calculate it that way.",
        "photo_fix_prompt": "Okay, send the photo again or describe what you ate as text.",
        "photo_no_grams_hint": "Amount in grams not specified, estimate from the photo if possible.",
        "btn_food_ok": "✅ Looks right",
        "btn_food_fix": "✏️ Fix",
        "remaining_header": "📊 Remaining today:",
        "remaining_line": "{label}: {eaten}/{target} {unit} ({remaining} {unit} left)\n{bar}",
        "today_entries_header": "Today's entries (tap to delete):",
        "entry_deleted": "Deleted ✅",
        "manage_entries_button": "✏️ Edit/delete entry",
        "confirm_delete_prompt": "Delete “{name}” — {kcal} {unit}?",
        "confirm_yes": "✅ Yes, delete",
        "confirm_no": "❌ Cancel",
        "history_choose_period": "Which period should I show?",
        "history_no_entries": "📅 No entries for {date_from} — {date_to}.",
        "history_header": "📅 History ({date_from} — {date_to}):\n",
        "history_total": "Total: {kcal} kcal, P {protein} / F {fat} / C {carbs}{weight_part}\n",
        "history_weight_part": ", weight {weight} kg",
        "history_period_today": "Today",
        "history_period_yesterday": "Yesterday",
        "history_period_week": "This week",
        "weight_checkin_prompt": "How's your weight this week?",
        "weight_checkin_now": "Enter weight now",
        "weight_checkin_skip": "Skip",
        "weight_checkin_ask": "Enter your current weight in kg:",
        "weight_checkin_skipped": "Okay, I'll ask again later. You can enter your weight any time via ⚙️ Settings.",
        "weight_checkin_saved": "Recorded: {value} kg, nice! 💪",
        "weight_reminder": "Don't forget to log your weight this week 🙂",
        "btn_settings": "⚙️ Settings",
        "btn_remaining": "📊 Remaining today",
        "btn_history": "📅 History",
        "help_text": (
            "Just tell me what you ate — I'll recognize the food and calculate calories/macros.\n"
            "You can send a photo of a label along with how many grams you ate.\n\n"
            "📊 Remaining today — how many calories/macros are left for today.\n"
            "📅 History — stats for past days.\n"
            "⚙️ Settings — change weight/height/age/goal/macros/API key."
        ),
        "fallback_text": "Not sure I understood. Tell me what you ate, send a food label photo, or use /help.",
        "generic_error": "Something went wrong. Please try again shortly.",
    },
    "he": {
        "language_prompt": "🌐 Выберите язык / Choose language / בחר שפה:",
        "language_saved": "בוצע ✅",
        "welcome": (
            "היי! אני אעזור לך לעקוב אחרי קלוריות ואבות מזון.\n\n"
            "אני משתמש במפתח ה-OpenAI API האישי שלך כדי לזהות אוכל מטקסט ותמונות — "
            "כל העלויות מחויבות ליתרת ה-OpenAI שלך, והמפתח נשמר מוצפן.\n\n"
            "בוא נגדיר את הפרופיל שלך."
        ),
        "welcome_back": "ברוך שובך! פשוט כתוב לי מה אכלת, או בחר פריט מהתפריט.",
        "ask_api_key": "הזן את מפתח ה-OpenAI API שלך (הוא משמש רק לבקשות שלך ונשמר מוצפן):",
        "checking_key": "רגע, בודק את המפתח... 🔑",
        "key_invalid": "המפתח לא תקין. אנא הזן מפתח OpenAI API תקין:",
        "key_check_failed": "לא הצלחתי להתחבר ל-OpenAI כדי לבדוק את המפתח. נסה לשלוח אותו שוב בעוד רגע:",
        "key_accepted_ask_weight": "המפתח התקבל ✅\n\nעכשיו הזן את משקלך בק\"ג (למשל 78.5):",
        "settings_ask_new_api_key": "הזן מפתח OpenAI API חדש:",
        "ask_weight": "הזן את משקלך בק\"ג (למשל 78.5):",
        "weight_invalid": "זה לא נראה כמו משקל. הזן מספר בק\"ג, למשל 78.5:",
        "ask_height": "גובה בס\"מ (למשל 178):",
        "height_invalid": "זה לא נראה כמו גובה. הזן מספר בס\"מ, למשל 178:",
        "ask_age": "גיל (שנים מלאות):",
        "age_invalid": "זה לא נראה כמו גיל. הזן מספר שנים, למשל 30:",
        "ask_gender": "מין:",
        "ask_activity": "רמת פעילות:",
        "ask_goal": "מה המטרה שלך?",
        "ask_deficit_loss": "באיזה אחוז לצמצם את הקלוריות?",
        "ask_deficit_gain": "באיזה אחוז להגדיל את הקלוריות?",
        "settings_ask_deficit": "באיזה אחוז לשנות את הקלוריות?",
        "gender_male": "זכר",
        "gender_female": "נקבה",
        "activity_sedentary": "יושבני",
        "activity_light": "פעילות קלה",
        "activity_moderate": "בינונית",
        "activity_high": "גבוהה",
        "activity_very_high": "גבוהה מאוד",
        "goal_loss": "ירידה במשקל",
        "goal_gain": "עלייה במשקל",
        "goal_maintain": "שמירה על המשקל",
        "gender_saved": "מין: {label} ✅",
        "activity_saved": "פעילות: {label} ✅",
        "goal_saved": "מטרה: {label} ✅",
        "deficit_saved": "אחוז גירעון/עודף: {value} ✅",
        "deficit_ai_suggest": "הבינה המלאכותית תציע",
        "computing_targets": "רגע, מחשב את יעדי הקלוריות ואבות המזון שלך... 🧮",
        "targets_proposed_header": "היעדים היומיים המוצעים:",
        "targets_current_header": "היעדים הנוכחיים:",
        "targets_line": "{label}: {value} {unit}",
        "targets_accept_or_edit": "אשר כפי שהם, או ערוך ערכים בודדים:",
        "targets_saved": "היעדים נשמרו, התחלה מצוינת! ✅",
        "targets_field_prompt": "הזן ערך חדש עבור “{field}”:",
        "targets_field_invalid": "הזן מספר שלם חיובי:",
        "onboarding_complete": "הפרופיל שלך מוכן! פשוט כתוב לי מה אכלת, בכל ניסוח.",
        "fallback_explanation": "הבינה המלאכותית אינה זמינה כרגע — מוצג חישוב משוער, ניתן לתקן את הערכים ידנית.",
        "target_kcal": "קלוריות",
        "target_protein": "חלבון",
        "target_fat": "שומן",
        "target_carbs": "פחמימות",
        "abbr_protein": "ח",
        "abbr_fat": "ש",
        "abbr_carbs": "פ",
        "unit_kcal": "קק\"ל",
        "unit_g": "גרם",
        "settings_incomplete_profile": "קודם יש להשלים את הגדרת הפרופיל דרך /start.",
        "settings_title": "⚙️ הגדרות:",
        "settings_saved": "נשמר ✅\n\n⚙️ הגדרות:",
        "settings_field_basic_info": "📋 פרטים בסיסיים",
        "settings_field_goal_activity": "🎯 מטרה ופעילות",
        "settings_field_weight": "משקל",
        "settings_field_height": "גובה",
        "settings_field_age": "גיל",
        "settings_field_gender": "מין",
        "settings_field_activity": "פעילות",
        "settings_field_goal": "מטרה",
        "settings_field_deficit": "אחוז גירעון/עודף",
        "settings_field_targets": "אבות מזון ידנית",
        "settings_field_update_weight": "⚖️ עדכון משקל",
        "settings_field_api_key": "🔑 מפתח API",
        "settings_field_language": "🌐 שפה",
        "food_no_api_key": "קודם הזן את מפתח ה-OpenAI API שלך דרך ⚙️ הגדרות.",
        "calculating": "רגע, מחשב קלוריות... 🧮",
        "food_item_parse_failed": "הממ, לא הצלחתי לזהות את “{text}”: {error}",
        "food_parse_network_error": "לא הצלחתי להתחבר ל-OpenAI. נסה לשלוח את ההודעה שוב בבקשה.",
        "food_nothing_recognized": "לא הצלחתי לזהות שום דבר 🤔 אנא פרט מה בדיוק אכלת וכמה גרם.",
        "ai_no_items_recognized": "לא הצלחתי לזהות פריטי מזון בהודעה.",
        "ai_invalid_response": "המודל החזיר תשובה לא תקינה, נסה לנסח מחדש את ההודעה.",
        "food_fix_prompt": "בסדר, שלח תיאור מתוקן של מה שאכלת.",
        "food_saved": "מעולה, נשמר! 🙌",
        "food_summary_header": "הנה מה שזיהיתי 🍽\n",
        "food_summary_total": "סה\"כ",
        "photo_ask_grams": "וכמה גרם אכלת?",
        "photo_lost_state": "אופס, משהו השתבש — שלח את התמונה שוב בבקשה.",
        "photo_recognizing": "רגע, מסתכל על התמונה... 👀",
        "photo_unreadable_suffix": "\nאנא תאר בטקסט מה אכלת, וכך אחשב.",
        "photo_fix_prompt": "בסדר, שלח את התמונה שוב או תאר בטקסט מה אכלת.",
        "photo_no_grams_hint": "כמות בגרמים לא צוינה, הערך לפי התמונה אם אפשר.",
        "btn_food_ok": "✅ הכל נכון",
        "btn_food_fix": "✏️ לתקן",
        "remaining_header": "📊 נותר להיום:",
        "remaining_line": "{label}: {eaten}/{target} {unit} (נותרו {remaining} {unit})\n{bar}",
        "today_entries_header": "רשומות היום (הקש כדי למחוק):",
        "entry_deleted": "נמחק ✅",
        "manage_entries_button": "✏️ עריכה/מחיקה של רשומה",
        "confirm_delete_prompt": "למחוק את “{name}” — {kcal} {unit}?",
        "confirm_yes": "✅ כן, למחוק",
        "confirm_no": "❌ ביטול",
        "history_choose_period": "עבור איזו תקופה להציג היסטוריה?",
        "history_no_entries": "📅 אין רשומות לתקופה {date_from} — {date_to}.",
        "history_header": "📅 היסטוריה ({date_from} — {date_to}):\n",
        "history_total": "סה\"כ: {kcal} קק\"ל, ח {protein} / ש {fat} / פ {carbs}{weight_part}\n",
        "history_weight_part": ", משקל {weight} ק\"ג",
        "history_period_today": "היום",
        "history_period_yesterday": "אתמול",
        "history_period_week": "השבוע",
        "weight_checkin_prompt": "מה המשקל שלך השבוע?",
        "weight_checkin_now": "הזן משקל עכשיו",
        "weight_checkin_skip": "דלג",
        "weight_checkin_ask": "הזן את משקלך הנוכחי בק\"ג:",
        "weight_checkin_skipped": "בסדר, אשאל שוב מאוחר יותר. אפשר להזין משקל בכל עת דרך ⚙️ הגדרות.",
        "weight_checkin_saved": "נרשם: {value} ק\"ג, כל הכבוד! 💪",
        "weight_reminder": "אל תשכח לעדכן את המשקל השבוע 🙂",
        "btn_settings": "⚙️ הגדרות",
        "btn_remaining": "📊 נותר להיום",
        "btn_history": "📅 היסטוריה",
        "help_text": (
            "פשוט כתוב לי מה אכלת — אזהה את המזון ואחשב קלוריות/אבות מזון.\n"
            "אפשר לשלוח תמונה של תווית עם ציון כמה גרם אכלת.\n\n"
            "📊 נותר להיום — כמה קלוריות/אבות מזון נותרו עד היעד.\n"
            "📅 היסטוריה — נתונים לימים קודמים.\n"
            "⚙️ הגדרות — שינוי משקל/גובה/גיל/מטרה/אבות מזון/מפתח API."
        ),
        "fallback_text": "לא הבנתי לגמרי. כתוב לי מה אכלת, שלח תמונת מזון עם תווית, או השתמש ב-/help.",
        "generic_error": "משהו השתבש. נסה שוב בעוד רגע.",
    },
}


def t(lang: str | None, key: str, **kwargs) -> str:
    lang = lang if lang in TEXTS else DEFAULT_LANGUAGE
    template = TEXTS[lang].get(key) or TEXTS[DEFAULT_LANGUAGE].get(key, key)
    return template.format(**kwargs) if kwargs else template


# A few high-frequency phrases get light variety so the bot doesn't repeat itself verbatim
# on every single food log — picked at random, not translated via `t()`.
VARIANTS: dict[str, dict[str, list[str]]] = {
    "ru": {
        "calculating": [
            "Секунду, считаю калории... 🧮",
            "Минутку, прикидываю КБЖУ... 🧮",
            "Ща посчитаю... 🧮",
        ],
        "food_saved": [
            "Готово, записал! 🙌",
            "Занёс в дневник ✅",
            "Есть, сохранил! 👍",
        ],
    },
    "en": {
        "calculating": [
            "One sec, calculating calories... 🧮",
            "Give me a moment, crunching the numbers... 🧮",
            "Let me work that out... 🧮",
        ],
        "food_saved": [
            "Done, saved it! 🙌",
            "Logged it ✅",
            "Got it, saved! 👍",
        ],
    },
    "he": {
        "calculating": [
            "רגע, מחשב קלוריות... 🧮",
            "שנייה, בודק את המספרים... 🧮",
            "תן לי לחשב... 🧮",
        ],
        "food_saved": [
            "מעולה, נשמר! 🙌",
            "נרשם ביומן ✅",
            "סגור, שמרתי! 👍",
        ],
    },
}


def t_random(lang: str | None, key: str) -> str:
    lang = lang if lang in VARIANTS else DEFAULT_LANGUAGE
    options = VARIANTS[lang].get(key)
    if not options:
        return t(lang, key)
    return random.choice(options)
